<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.t.d.l3U' shared service.

return $this->privates['.service_locator.t.d.l3U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'reservering' => ['privates', '.errored..service_locator.t.d.l3U.App\\Entity\\Reservering', NULL, 'Cannot autowire service ".service_locator.t.d.l3U": it references class "App\\Entity\\Reservering" but no such service exists.'],
]);
