<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RV65.Hz' shared service.

return $this->privates['.service_locator.RV65.Hz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'kamer' => ['privates', '.errored..service_locator.RV65.Hz.App\\Entity\\Kamer', NULL, 'Cannot autowire service ".service_locator.RV65.Hz": it references class "App\\Entity\\Kamer" but no such service exists.'],
]);
