<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._C7mJYY' shared service.

return $this->privates['.service_locator._C7mJYY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'seizoenRepository' => ['privates', 'App\\Repository\\SeizoenRepository', 'getSeizoenRepositoryService.php', true],
]);
