<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.D3jgiPx' shared service.

return $this->privates['.service_locator.D3jgiPx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'betaalRepository' => ['privates', 'App\\Repository\\BetaalRepository', 'getBetaalRepositoryService.php', true],
]);
