<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nVaURA1' shared service.

return $this->privates['.service_locator.nVaURA1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'betaal' => ['privates', '.errored..service_locator.nVaURA1.App\\Entity\\Betaal', NULL, 'Cannot autowire service ".service_locator.nVaURA1": it references class "App\\Entity\\Betaal" but no such service exists.'],
]);
