<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IB3xp6Q' shared service.

return $this->privates['.service_locator.IB3xp6Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'seizoen' => ['privates', '.errored..service_locator.IB3xp6Q.App\\Entity\\Seizoen', NULL, 'Cannot autowire service ".service_locator.IB3xp6Q": it references class "App\\Entity\\Seizoen" but no such service exists.'],
]);
