<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.y3AzfhI' shared service.

return $this->privates['.service_locator.y3AzfhI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'soort' => ['privates', '.errored..service_locator.y3AzfhI.App\\Entity\\Soort', NULL, 'Cannot autowire service ".service_locator.y3AzfhI": it references class "App\\Entity\\Soort" but no such service exists.'],
]);
