<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBXDHp0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBXDHp0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBXDHp0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBXDHp0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHBXDHp0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HBXDHp0',
    'container.build_id' => '3bcfb1e9',
    'container.build_time' => 1560102799,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBXDHp0');
