<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFocl9xd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFocl9xd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFocl9xd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFocl9xd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFocl9xd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Focl9xd',
    'container.build_id' => '4d5a7633',
    'container.build_time' => 1561322569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFocl9xd');
